apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f services/docker-compose-prod-fmp.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: indexing-service
  name: indexing-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: indexing-service
status:
  loadBalancer: {}
