apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f services/docker-compose-prod-fmp.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: business-process-service
  name: business-process-service
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    io.kompose.service: business-process-service
status:
  loadBalancer: {}
