apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f infra/solr/docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: solr

    spec:
      initContainers:
      - name: chmod-er
        image: busybox:latest
        command:
        - /bin/chown
        - -R
        - 8983:8983 # or whatever the mongo UID is
        - /data
        volumeMounts:
        - name: solr-data  # or whatever
          mountPath: /data/
      containers:
      - name: nginx
        image: beevelop/nginx-basic-auth
        env:
    
        ports:
          - containerPort: 80
      - args:
        - -cloud
        image: solr:7.6.0
        name: solr
        ports:
        - containerPort: 8983
        resources: {}
        volumeMounts:
        - mountPath: /opt/solr/server/solr/mycore
          name: solr-data
      restartPolicy: Always
      volumes:
      - name: solr-data
        # Uncomment if using PVC (Configure the solr-data-persistentvolumeclaim.yaml)
        # persistentVolumeClaim:
        #   claimName: solr-data
        hostPath:
          path: /kubernetesStorage/solr/
status: {}
